REDIS_HOST=i14d104.p.ssafy.io
REDIS_PORT=8920

MONGO_USER=root
MONGO_PASSWORD=D104!!
MONGO_HOST=i14d104.p.ssafy.io
MONGO_PORT=8910
MONGO_DB_NAME=pnt

MQ_IMAGE=IMAGE
MQ_ALARM=ALARM
MQ_NEWS=NEWS
EXCHANGE_NAME=E1
MQ_HOST=i14d104.p.ssafy.io
MQ_PORT=8930
MQ_USER=root
MQ_PASSWORD=D104!!

JWT_SECRET=fH7vQVHckJD0PaQqmZwAx+LZvlBGhU0Yf3MfzRECq+TrsbeFOq19Q0iZCsw0OAnKbI6DlxUF9LVv9lWm+HC9qg==

POSTGRES_DB_NAME=pnt
POSTGRES_USER=root
POSTGRES_PASSWORD=D104!!
POSTGRES_HOST=i14d104.p.ssafy.io
POSTGRES_PORT=8900