REDIS_HOST_SECRET=localhost
REDIS_PORT_SECRET=8920
MONGO_USER_SECRET=root
MONGO_PASSWORD_SECRET=D104!!
MONGO_HOST_SECRET=localhost
MONGO_PORT_SECRET=8910
MONGO_DB_NAME_SECRET=pnt
MQ_IMAGE_SECRET=IMAGE
MQ_ALARM_SECRET=ALARM
MQ_NEWS_SECRET=NEWS
EXCHANGE_NAME=E1
MQ_HOST_SECRET=localhost
MQ_PORT_SECRET=8930
MQ_USER_SECRET=root
MQ_PASSWORD_SECRET=D104!!
JWT_SECRET_SECRET=fH7vQVHckJD0PaQqmZwAx+LZvlBGhU0Yf3MfzRECq+TrsbeFOq19Q0iZCsw0OAnKbI6DlxUF9LVv9lWm+HC9qg==
POSTGRES_DB_NAME_SECRET=pnt
POSTGRES_USER_SECRET=root
POSTGRES_PASSWORD_SECRET=D104!!
POSTGRES_HOST_SECRET=localhost
POSTGRES_PORT_SECRET=8900
KAKAO_APP_ID_SECRET=1371114
AWS_S3_BUCKET_NAME_SECRET=pnt-s3-bucket
AWS_ACCESS_KEY_SECRET=AKIAYZPMOIFN3GHBLQFT
AWS_SECRET_KEY_SECRET=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
AWS_REGION_SECRET=ap-northeast-2