DATABASE_URL=jdbc:postgresql://localhost:5432/pnt
USER_NAME=postgres
PASSWORD=1234

# ?? ??? base64 ? ??
JWT_SECRET=fH7vQVHckJD0PaQqmZwAx+LZvlBGhU0Yf3MfzRECq+TrsbeFOq19Q0iZCsw0OAnKbI6DlxUF9LVv9lWm+HC9qg==