DATABASE_URL=jdbc:postgresql://localhost:5432/pnt
USER_NAME=postgres
PASSWORD=1234

jwt.secret=QkFTRTY0X0pXVF9TRUNSRVRfS0VZX1BOVF9QUk9KRUNUX1NFQ1VSRV9MT0NBTF9ERVZfS0VZXzIwMjZfU1RSSU5HX1RPS0VOX1NFQ1JFVF9LRVk=
