--
-- PostgreSQL database dump
--

\restrict pkjpPWqbqrFezagNtSuTaE0MJjM5f1XQpzftr99191zgndK4tcRgFF9wLrMCbsr

-- Dumped from database version 15.4 (Debian 15.4-1.pgdg110+1)
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: chat_room; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.chat_room (
    current_members integer NOT NULL,
    is_deleted boolean,
    max_members integer NOT NULL,
    region_code integer NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    owner_id bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    description text,
    title character varying(255) NOT NULL
);


ALTER TABLE public.chat_room OWNER TO root;

--
-- Name: chat_room_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.chat_room ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_room_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: chat_room; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.chat_room (current_members, is_deleted, max_members, region_code, created_at, id, owner_id, updated_at, description, title) FROM stdin;
2	f	2	0	2026-02-01 00:06:24.639074+09	1	2	2026-02-01 00:07:35.65484+09	string	string
\.


--
-- Name: chat_room_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.chat_room_id_seq', 1, true);


--
-- Name: chat_room chat_room_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.chat_room
    ADD CONSTRAINT chat_room_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict pkjpPWqbqrFezagNtSuTaE0MJjM5f1XQpzftr99191zgndK4tcRgFF9wLrMCbsr

