--
-- PostgreSQL database dump
--

\restrict 2pS16X7CWfp4tNcN3rHmuNjLQuiL6EQEPEwUGvMakemx3Df9uo1ghELI3PHJadA

-- Dumped from database version 15.4 (Debian 15.4-1.pgdg110+1)
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: chat_room_ban; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.chat_room_ban (
    banned_at timestamp(6) with time zone NOT NULL,
    banned_by bigint NOT NULL,
    banned_until timestamp(6) with time zone NOT NULL,
    chat_room_id bigint NOT NULL,
    id bigint NOT NULL,
    member_id bigint NOT NULL,
    reason character varying(255)
);


ALTER TABLE public.chat_room_ban OWNER TO root;

--
-- Name: chat_room_ban_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.chat_room_ban ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_room_ban_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: chat_room_ban; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.chat_room_ban (banned_at, banned_by, banned_until, chat_room_id, id, member_id, reason) FROM stdin;
\.


--
-- Name: chat_room_ban_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.chat_room_ban_id_seq', 1, false);


--
-- Name: chat_room_ban chat_room_ban_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.chat_room_ban
    ADD CONSTRAINT chat_room_ban_pkey PRIMARY KEY (id);


--
-- Name: chat_room_ban uq_chat_room_ban_room_member; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.chat_room_ban
    ADD CONSTRAINT uq_chat_room_ban_room_member UNIQUE (chat_room_id, member_id);


--
-- Name: idx_chat_room_ban_lookup; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX idx_chat_room_ban_lookup ON public.chat_room_ban USING btree (chat_room_id, member_id, banned_until);


--
-- Name: chat_room_ban fk1jd5ht5d8ky50jnvstf5mqldf; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.chat_room_ban
    ADD CONSTRAINT fk1jd5ht5d8ky50jnvstf5mqldf FOREIGN KEY (chat_room_id) REFERENCES public.chat_room(id);


--
-- Name: chat_room_ban fkoei0mmp8ar9um2on04bj8uegc; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.chat_room_ban
    ADD CONSTRAINT fkoei0mmp8ar9um2on04bj8uegc FOREIGN KEY (banned_by) REFERENCES public.member(id);


--
-- Name: chat_room_ban fkowt13gw25605m7ih205j6tjtt; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.chat_room_ban
    ADD CONSTRAINT fkowt13gw25605m7ih205j6tjtt FOREIGN KEY (member_id) REFERENCES public.member(id);


--
-- PostgreSQL database dump complete
--

\unrestrict 2pS16X7CWfp4tNcN3rHmuNjLQuiL6EQEPEwUGvMakemx3Df9uo1ghELI3PHJadA

