--
-- PostgreSQL database dump
--

\restrict c8FRjbACGUEyau2gFESxw4oBD9uaU7bI0draxPcOBBXoN2D6XpqMmLXEST7cHGc

-- Dumped from database version 15.4 (Debian 15.4-1.pgdg110+1)
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: game_member; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.game_member (
    in_game_connected boolean,
    is_deleted boolean,
    ready boolean NOT NULL,
    status smallint,
    created_at timestamp(6) with time zone NOT NULL,
    game_id bigint NOT NULL,
    id bigint NOT NULL,
    member_id bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    prefer_position character varying(10) NOT NULL,
    given_position character varying(20),
    serial_code character varying(255),
    CONSTRAINT game_member_given_position_check CHECK (((given_position)::text = ANY ((ARRAY['POLICE'::character varying, 'POLICE_CHIEF'::character varying, 'THIEF'::character varying])::text[]))),
    CONSTRAINT game_member_prefer_position_check CHECK (((prefer_position)::text = ANY ((ARRAY['POLICE'::character varying, 'THIEF'::character varying, 'ANY'::character varying])::text[]))),
    CONSTRAINT game_member_status_check CHECK (((status >= 0) AND (status <= 2)))
);


ALTER TABLE public.game_member OWNER TO root;

--
-- Name: game_member_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.game_member ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.game_member_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: game_member; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.game_member (in_game_connected, is_deleted, ready, status, created_at, game_id, id, member_id, updated_at, prefer_position, given_position, serial_code) FROM stdin;
f	t	t	\N	2026-01-30 23:07:26.648047+09	2	8	6	2026-01-30 23:07:26.648047+09	ANY	\N	\N
\N	f	t	\N	2026-01-31 20:08:26.537414+09	3	10	7	2026-01-31 20:34:31.430179+09	ANY	\N	\N
\N	f	t	\N	2026-01-31 20:09:17.379744+09	3	11	8	2026-01-31 20:34:31.430188+09	ANY	\N	\N
t	t	t	\N	2026-01-30 20:55:53.579122+09	1	1	1	2026-02-05 01:59:04.620225+09	ANY	\N	\N
t	t	t	\N	2026-01-30 20:58:12.679359+09	1	2	2	2026-02-05 01:59:04.620289+09	ANY	\N	\N
t	t	t	\N	2026-01-30 20:58:58.743609+09	1	3	3	2026-02-05 01:59:04.620318+09	ANY	\N	\N
f	t	f	\N	2026-01-30 23:06:48.999495+09	1	7	6	2026-02-02 20:59:53.492074+09	ANY	\N	\N
t	t	t	\N	2026-01-30 20:59:18.957611+09	1	4	4	2026-02-05 01:59:04.620341+09	ANY	\N	\N
t	t	t	\N	2026-01-30 20:59:50.977302+09	1	5	5	2026-02-05 01:59:04.620382+09	ANY	\N	\N
f	t	t	\N	2026-01-30 23:08:42.75272+09	2	9	3	2026-01-30 23:08:42.75272+09	ANY	\N	\N
\N	t	f	\N	2026-02-05 20:05:59.656412+09	4	15	4	2026-02-05 20:52:33.167084+09	ANY	\N	\N
\N	t	f	\N	2026-02-05 20:06:11.024528+09	4	16	5	2026-02-05 20:52:33.167163+09	ANY	\N	\N
\N	t	f	\N	2026-02-05 19:59:15.058667+09	4	12	1	2026-02-05 20:53:33.659201+09	ANY	\N	\N
\N	t	f	\N	2026-02-05 19:59:48.520468+09	4	13	2	2026-02-05 20:53:33.659275+09	ANY	\N	\N
\N	t	f	\N	2026-02-05 20:05:46.068781+09	4	14	3	2026-02-05 20:53:33.659336+09	ANY	\N	\N
\.


--
-- Name: game_member_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.game_member_id_seq', 16, true);


--
-- Name: game_member game_member_game_id_member_id_key; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.game_member
    ADD CONSTRAINT game_member_game_id_member_id_key UNIQUE (game_id, member_id);


--
-- Name: game_member game_member_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.game_member
    ADD CONSTRAINT game_member_pkey PRIMARY KEY (id);


--
-- Name: game_member uk4igvra6yofh6udqwkfaa8hv8d; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.game_member
    ADD CONSTRAINT uk4igvra6yofh6udqwkfaa8hv8d UNIQUE (game_id, member_id);


--
-- Name: game_member_game_id_member_id; Type: INDEX; Schema: public; Owner: root
--

CREATE UNIQUE INDEX game_member_game_id_member_id ON public.game_member USING btree (game_id, member_id);


--
-- Name: game_member fkaqysopurh7v9aji75hct59qbi; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.game_member
    ADD CONSTRAINT fkaqysopurh7v9aji75hct59qbi FOREIGN KEY (game_id) REFERENCES public.game(id);


--
-- Name: game_member fkersd2yd18a8kd000irs2h1dtu; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.game_member
    ADD CONSTRAINT fkersd2yd18a8kd000irs2h1dtu FOREIGN KEY (member_id) REFERENCES public.member(id);


--
-- PostgreSQL database dump complete
--

\unrestrict c8FRjbACGUEyau2gFESxw4oBD9uaU7bI0draxPcOBBXoN2D6XpqMmLXEST7cHGc

