--
-- PostgreSQL database dump
--

\restrict KK2YErU3HnyqpLAiyPwmIrRdxN66SC9pELbGoahuWndXYlWT8KVxxb0JldfXKr7

-- Dumped from database version 15.4 (Debian 15.4-1.pgdg110+1)
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: game_news; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.game_news (
    is_deleted boolean,
    created_at timestamp(6) with time zone NOT NULL,
    game_id bigint NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    title character varying(255),
    content text
);


ALTER TABLE public.game_news OWNER TO root;

--
-- Name: game_news_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.game_news ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.game_news_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: game_news; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.game_news (is_deleted, created_at, game_id, id, updated_at, title, content) FROM stdin;
\.


--
-- Name: game_news_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.game_news_id_seq', 1, false);


--
-- Name: game_news game_news_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.game_news
    ADD CONSTRAINT game_news_pkey PRIMARY KEY (id);


--
-- Name: game_news fkihkk3nhokqt12rjwynikmown5; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.game_news
    ADD CONSTRAINT fkihkk3nhokqt12rjwynikmown5 FOREIGN KEY (game_id) REFERENCES public.game(id);


--
-- PostgreSQL database dump complete
--

\unrestrict KK2YErU3HnyqpLAiyPwmIrRdxN66SC9pELbGoahuWndXYlWT8KVxxb0JldfXKr7

