--
-- PostgreSQL database dump
--

\restrict Fg8KB1HAKj89ldieQM4siGq42p8yfvi6gZelJz2HbEchHd2HvqXk2Rqw5dSsK5v

-- Dumped from database version 15.4 (Debian 15.4-1.pgdg110+1)
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: game; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.game (
    caught_count integer NOT NULL,
    is_deleted boolean,
    created_at timestamp(6) with time zone NOT NULL,
    end_time timestamp(6) with time zone,
    host_member_id bigint NOT NULL,
    id bigint NOT NULL,
    start_time timestamp(6) with time zone,
    updated_at timestamp(6) with time zone NOT NULL,
    room_code character varying(10) NOT NULL,
    status character varying(20) NOT NULL,
    win_team character varying(20) NOT NULL,
    CONSTRAINT game_status_check CHECK (((status)::text = ANY ((ARRAY['WAITING'::character varying, 'IN_GAME'::character varying, 'ENDED'::character varying])::text[]))),
    CONSTRAINT game_win_team_check CHECK (((win_team)::text = ANY ((ARRAY['POLICE'::character varying, 'THIEF'::character varying, 'NONE'::character varying])::text[])))
);


ALTER TABLE public.game OWNER TO root;

--
-- Name: game_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.game ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.game_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: game; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.game (caught_count, is_deleted, created_at, end_time, host_member_id, id, start_time, updated_at, room_code, status, win_team) FROM stdin;
0	t	2026-01-30 20:55:53.547186+09	\N	2	1	\N	2026-02-05 01:59:04.711573+09	Q5AEWX	WAITING	NONE
0	f	2026-01-30 23:07:26.639099+09	\N	6	2	\N	2026-01-30 23:07:26.639099+09	XFZAQT	WAITING	NONE
0	f	2026-01-31 20:08:26.530251+09	2026-01-31 20:34:31.414217+09	7	3	2026-01-31 20:33:39.626+09	2026-01-31 20:34:31.430097+09	8JGNV7	ENDED	POLICE
0	f	2026-02-05 19:59:15.006848+09	\N	1	4	\N	2026-02-05 20:53:33.750072+09	XUAQ7Y	WAITING	NONE
\.


--
-- Name: game_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.game_id_seq', 4, true);


--
-- Name: game game_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.game
    ADD CONSTRAINT game_pkey PRIMARY KEY (id);


--
-- Name: game game_room_code_key; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.game
    ADD CONSTRAINT game_room_code_key UNIQUE (room_code);


--
-- Name: game fkgvvw98ofrnwx5biaapirc0b9q; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.game
    ADD CONSTRAINT fkgvvw98ofrnwx5biaapirc0b9q FOREIGN KEY (host_member_id) REFERENCES public.member(id);


--
-- PostgreSQL database dump complete
--

\unrestrict Fg8KB1HAKj89ldieQM4siGq42p8yfvi6gZelJz2HbEchHd2HvqXk2Rqw5dSsK5v

