--
-- PostgreSQL database dump
--

\restrict KAPJanNcehcPcz3KReNpLUmtHYdqfoE3YrElGRYC7B0CW3z8WTPmiHEKml82Qrk

-- Dumped from database version 15.4 (Debian 15.4-1.pgdg110+1)
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: game_mission; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.game_mission (
    is_deleted boolean,
    completed_at timestamp(6) with time zone,
    completed_by bigint,
    created_at timestamp(6) with time zone NOT NULL,
    game_id bigint NOT NULL,
    id bigint NOT NULL,
    mission_id bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    status character varying(255),
    CONSTRAINT game_mission_status_check CHECK (((status)::text = ANY ((ARRAY['IN_PROGRESS'::character varying, 'SUCCESS'::character varying])::text[])))
);


ALTER TABLE public.game_mission OWNER TO root;

--
-- Name: game_mission_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.game_mission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.game_mission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: game_mission; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.game_mission (is_deleted, completed_at, completed_by, created_at, game_id, id, mission_id, updated_at, status) FROM stdin;
f	\N	\N	2026-02-03 01:24:47.268872+09	1	1	8	2026-02-03 01:24:47.268872+09	IN_PROGRESS
f	\N	\N	2026-02-05 01:57:36.281337+09	1	3	11	2026-02-05 01:57:36.281337+09	IN_PROGRESS
f	2026-02-05 20:08:04.886+09	2	2026-02-05 00:53:47.489535+09	1	2	6	2026-02-05 20:08:04.886+09	SUCCESS
f	\N	\N	2026-02-05 20:36:54.158015+09	4	5	6	2026-02-05 20:36:54.158015+09	IN_PROGRESS
f	\N	\N	2026-02-05 20:06:46.592767+09	4	4	2	2026-02-05 20:51:59.778+09	IN_PROGRESS
\.


--
-- Name: game_mission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.game_mission_id_seq', 5, true);


--
-- Name: game_mission game_mission_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.game_mission
    ADD CONSTRAINT game_mission_pkey PRIMARY KEY (id);


--
-- Name: game_mission fk35e4q6h8mfrgdfmw0eidp4xvs; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.game_mission
    ADD CONSTRAINT fk35e4q6h8mfrgdfmw0eidp4xvs FOREIGN KEY (completed_by) REFERENCES public.member(id);


--
-- Name: game_mission fkcl90xbu4c0hqijv0wasvl2a1p; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.game_mission
    ADD CONSTRAINT fkcl90xbu4c0hqijv0wasvl2a1p FOREIGN KEY (game_id) REFERENCES public.game(id);


--
-- Name: game_mission fkh040ia12hq7bk21tk6qmo600f; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.game_mission
    ADD CONSTRAINT fkh040ia12hq7bk21tk6qmo600f FOREIGN KEY (mission_id) REFERENCES public.mission(id);


--
-- PostgreSQL database dump complete
--

\unrestrict KAPJanNcehcPcz3KReNpLUmtHYdqfoE3YrElGRYC7B0CW3z8WTPmiHEKml82Qrk

