--
-- PostgreSQL database dump
--

\restrict uaiwp8xpinxaEfh8kZcrEIWEhHY8oRIcv06yruVaKOLw5dMweWVUkTIkcGhZbIr

-- Dumped from database version 15.4 (Debian 15.4-1.pgdg110+1)
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: game_member_stat; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.game_member_stat (
    arrest_count integer,
    escape_count integer,
    is_deleted boolean,
    longest_survived integer,
    walk integer,
    created_at timestamp(6) with time zone NOT NULL,
    game_member_id bigint NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    "position" character varying(255),
    mission_count integer,
    CONSTRAINT game_member_stat_position_check CHECK ((("position")::text = ANY ((ARRAY['POLICE'::character varying, 'POLICE_CHIEF'::character varying, 'THIEF'::character varying])::text[])))
);


ALTER TABLE public.game_member_stat OWNER TO root;

--
-- Name: game_member_stat_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.game_member_stat ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.game_member_stat_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: game_member_stat; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.game_member_stat (arrest_count, escape_count, is_deleted, longest_survived, walk, created_at, game_member_id, id, updated_at, "position", mission_count) FROM stdin;
0	\N	f	0	0	2026-01-31 20:10:19.691995+09	10	6	2026-01-31 20:10:19.691995+09	THIEF	\N
0	\N	f	0	0	2026-01-31 20:10:19.693603+09	11	7	2026-01-31 20:10:19.693603+09	POLICE	\N
0	\N	f	0	0	2026-01-31 20:12:47.673308+09	8	9	2026-01-31 20:12:47.673308+09	\N	\N
0	\N	f	0	0	2026-01-31 16:24:14.763536+09	5	5	2026-02-05 01:58:04.176+09	POLICE	\N
0	\N	f	0	0	2026-01-31 16:24:14.756837+09	2	2	2026-01-31 16:24:14.756837+09	THIEF	\N
0	\N	f	0	0	2026-01-31 16:24:14.759481+09	3	3	2026-01-31 16:24:14.759481+09	THIEF	\N
0	\N	f	0	0	2026-01-31 16:24:14.761509+09	4	4	2026-01-31 16:24:14.761509+09	THIEF	\N
0	\N	f	0	0	2026-01-31 20:12:47.650283+09	7	8	2026-01-31 20:12:47.650283+09	\N	\N
0	\N	f	0	0	2026-01-31 16:24:14.749522+09	1	1	2026-01-31 21:22:21.641431+09	THIEF	\N
0	\N	f	0	0	2026-02-05 20:06:46.613817+09	15	13	2026-02-05 20:06:46.613817+09	POLICE	\N
0	\N	f	0	0	2026-02-05 20:06:46.616914+09	16	14	2026-02-05 20:06:46.616914+09	POLICE	\N
0	\N	f	0	0	2026-02-05 20:06:46.600194+09	12	10	2026-02-05 20:52:32.900055+09	THIEF	1
0	\N	f	0	0	2026-02-05 20:06:46.606971+09	13	11	2026-02-05 20:52:32.93187+09	THIEF	0
0	\N	f	0	0	2026-02-05 20:06:46.610369+09	14	12	2026-02-05 20:52:33.167354+09	THIEF	0
\.


--
-- Name: game_member_stat_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.game_member_stat_id_seq', 14, true);


--
-- Name: game_member_stat game_member_stat_game_member_id_key; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.game_member_stat
    ADD CONSTRAINT game_member_stat_game_member_id_key UNIQUE (game_member_id);


--
-- Name: game_member_stat game_member_stat_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.game_member_stat
    ADD CONSTRAINT game_member_stat_pkey PRIMARY KEY (id);


--
-- Name: game_member_stat uk2tfuotnk3kmnhx12fek6ck6yc; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.game_member_stat
    ADD CONSTRAINT uk2tfuotnk3kmnhx12fek6ck6yc UNIQUE (game_member_id);


--
-- Name: game_member_stat fkhad7yfho1cqtrl28xb20s69y5; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.game_member_stat
    ADD CONSTRAINT fkhad7yfho1cqtrl28xb20s69y5 FOREIGN KEY (game_member_id) REFERENCES public.game_member(id);


--
-- PostgreSQL database dump complete
--

\unrestrict uaiwp8xpinxaEfh8kZcrEIWEhHY8oRIcv06yruVaKOLw5dMweWVUkTIkcGhZbIr

