--
-- PostgreSQL database dump
--

\restrict sneFXFNBdYioVr1u4w1R6woN2OXoShJhPVMFPWFb0vhLcml9Zj87N392zsjcs1z

-- Dumped from database version 15.4 (Debian 15.4-1.pgdg110+1)
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: game_skill; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.game_skill (
    is_deleted boolean,
    is_used boolean NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    game_id bigint NOT NULL,
    id bigint NOT NULL,
    member_id bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    used_at timestamp(6) with time zone
);


ALTER TABLE public.game_skill OWNER TO root;

--
-- Name: game_skill_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.game_skill ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.game_skill_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: game_skill; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.game_skill (is_deleted, is_used, created_at, game_id, id, member_id, updated_at, used_at) FROM stdin;
f	f	2026-01-31 20:10:19.689097+09	3	2	8	2026-01-31 20:10:19.689097+09	\N
f	f	2026-01-31 16:24:14.702329+09	1	1	1	2026-01-31 16:24:14.702329+09	\N
f	f	2026-01-31 21:22:21.610494+09	1	3	5	2026-02-04 00:06:24.116+09	\N
f	f	2026-02-05 20:06:46.580057+09	4	4	5	2026-02-05 20:06:46.580057+09	\N
\.


--
-- Name: game_skill_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.game_skill_id_seq', 4, true);


--
-- Name: game_skill game_skill_game_id_member_id_key; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.game_skill
    ADD CONSTRAINT game_skill_game_id_member_id_key UNIQUE (game_id, member_id);


--
-- Name: game_skill game_skill_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.game_skill
    ADD CONSTRAINT game_skill_pkey PRIMARY KEY (id);


--
-- Name: game_skill ukl67s2m7dexhau7k7662tn76ig; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.game_skill
    ADD CONSTRAINT ukl67s2m7dexhau7k7662tn76ig UNIQUE (game_id, member_id);


--
-- Name: game_skill_game_id_member_id; Type: INDEX; Schema: public; Owner: root
--

CREATE UNIQUE INDEX game_skill_game_id_member_id ON public.game_skill USING btree (game_id, member_id);


--
-- Name: game_skill fkimqbn3h8hb3s7knitnvp0o73v; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.game_skill
    ADD CONSTRAINT fkimqbn3h8hb3s7knitnvp0o73v FOREIGN KEY (game_id) REFERENCES public.game(id);


--
-- Name: game_skill fkq562uxt3j5caotmcn9bn6rool; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.game_skill
    ADD CONSTRAINT fkq562uxt3j5caotmcn9bn6rool FOREIGN KEY (member_id) REFERENCES public.member(id);


--
-- PostgreSQL database dump complete
--

\unrestrict sneFXFNBdYioVr1u4w1R6woN2OXoShJhPVMFPWFb0vhLcml9Zj87N392zsjcs1z

