--
-- PostgreSQL database dump
--

\restrict wTPdJI6eDmHc0l3C8njJ3SFSgCTTz2dtmUyR25Kxuag7QaCehz520DpDjAxhops

-- Dumped from database version 15.4 (Debian 15.4-1.pgdg110+1)
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: grade_police; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.grade_police (
    is_deleted boolean,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    name character varying(10)
);


ALTER TABLE public.grade_police OWNER TO root;

--
-- Name: grade_police_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.grade_police ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.grade_police_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: grade_police; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.grade_police (is_deleted, created_at, id, updated_at, name) FROM stdin;
f	2026-01-30 20:44:38.165523+09	1	2026-01-30 20:44:38.165523+09	순경
f	2026-01-30 20:44:38.165523+09	2	2026-01-30 20:44:38.165523+09	경장
f	2026-01-30 20:44:38.165523+09	3	2026-01-30 20:44:38.165523+09	경사
f	2026-01-30 20:44:38.165523+09	4	2026-01-30 20:44:38.165523+09	경위
f	2026-01-30 20:44:38.165523+09	5	2026-01-30 20:44:38.165523+09	경감
f	2026-01-30 20:44:38.165523+09	6	2026-01-30 20:44:38.165523+09	경정
f	2026-01-30 20:44:38.165523+09	7	2026-01-30 20:44:38.165523+09	총경
f	2026-01-30 20:44:38.165523+09	8	2026-01-30 20:44:38.165523+09	경무관
f	2026-01-30 20:44:38.165523+09	9	2026-01-30 20:44:38.165523+09	치안감
f	2026-01-30 20:44:38.165523+09	10	2026-01-30 20:44:38.165523+09	치안정감
f	2026-01-30 20:44:38.165523+09	11	2026-01-30 20:44:38.165523+09	치안총감
\.


--
-- Name: grade_police_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.grade_police_id_seq', 1, false);


--
-- Name: grade_police grade_police_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.grade_police
    ADD CONSTRAINT grade_police_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict wTPdJI6eDmHc0l3C8njJ3SFSgCTTz2dtmUyR25Kxuag7QaCehz520DpDjAxhops

