--
-- PostgreSQL database dump
--

\restrict nO0UVkYOT5wimy6FVxwCgkmfmemBbS8fLVzu1mxdeCg1nCdhcTonYD3kWBP1AkM

-- Dumped from database version 15.4 (Debian 15.4-1.pgdg110+1)
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: grade_thief; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.grade_thief (
    is_deleted boolean,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    name character varying(10)
);


ALTER TABLE public.grade_thief OWNER TO root;

--
-- Name: grade_thief_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.grade_thief ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.grade_thief_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: grade_thief; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.grade_thief (is_deleted, created_at, id, updated_at, name) FROM stdin;
f	2026-01-30 20:44:38.15992+09	1	2026-01-30 20:44:38.15992+09	바늘도둑
f	2026-01-30 20:44:38.15992+09	2	2026-01-30 20:44:38.15992+09	좀도둑
f	2026-01-30 20:44:38.15992+09	3	2026-01-30 20:44:38.15992+09	소매치기
f	2026-01-30 20:44:38.15992+09	4	2026-01-30 20:44:38.15992+09	빈집털이
f	2026-01-30 20:44:38.15992+09	5	2026-01-30 20:44:38.15992+09	소도둑
f	2026-01-30 20:44:38.15992+09	6	2026-01-30 20:44:38.15992+09	금고털이
f	2026-01-30 20:44:38.15992+09	7	2026-01-30 20:44:38.15992+09	은행털이
f	2026-01-30 20:44:38.15992+09	8	2026-01-30 20:44:38.15992+09	홍길동
f	2026-01-30 20:44:38.15992+09	9	2026-01-30 20:44:38.15992+09	인비져블
f	2026-01-30 20:44:38.15992+09	10	2026-01-30 20:44:38.15992+09	괴도
f	2026-01-30 20:44:38.15992+09	11	2026-01-30 20:44:38.15992+09	대도
\.


--
-- Name: grade_thief_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.grade_thief_id_seq', 1, false);


--
-- Name: grade_thief grade_thief_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.grade_thief
    ADD CONSTRAINT grade_thief_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict nO0UVkYOT5wimy6FVxwCgkmfmemBbS8fLVzu1mxdeCg1nCdhcTonYD3kWBP1AkM

