--
-- PostgreSQL database dump
--

\restrict aVnQEZttTqEEp0PUaa8uRcTLT1Hq1LQrqhOsYVc2QE7B3uV03hvqP50EYZmJy9w

-- Dumped from database version 15.4 (Debian 15.4-1.pgdg110+1)
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: member_auth_providers; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.member_auth_providers (
    is_deleted boolean,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    member_id bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    provider character varying(10) NOT NULL,
    provider_user_key character varying(255) NOT NULL
);


ALTER TABLE public.member_auth_providers OWNER TO root;

--
-- Name: member_auth_providers_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.member_auth_providers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.member_auth_providers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: member_auth_providers; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.member_auth_providers (is_deleted, created_at, id, member_id, updated_at, provider, provider_user_key) FROM stdin;
\.


--
-- Name: member_auth_providers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.member_auth_providers_id_seq', 1, false);


--
-- Name: member_auth_providers member_auth_providers_member_id_key; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.member_auth_providers
    ADD CONSTRAINT member_auth_providers_member_id_key UNIQUE (member_id);


--
-- Name: member_auth_providers member_auth_providers_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.member_auth_providers
    ADD CONSTRAINT member_auth_providers_pkey PRIMARY KEY (id);


--
-- Name: member_auth_providers member_auth_providers_provider_provider_user_key_key; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.member_auth_providers
    ADD CONSTRAINT member_auth_providers_provider_provider_user_key_key UNIQUE (provider, provider_user_key);


--
-- Name: member_auth_providers ukgbdksbhn0v1f73cl3wpl3g8u7; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.member_auth_providers
    ADD CONSTRAINT ukgbdksbhn0v1f73cl3wpl3g8u7 UNIQUE (provider, provider_user_key);


--
-- Name: member_auth_providers_provider_provider_user_key; Type: INDEX; Schema: public; Owner: root
--

CREATE UNIQUE INDEX member_auth_providers_provider_provider_user_key ON public.member_auth_providers USING btree (provider, provider_user_key);


--
-- Name: member_auth_providers fkl5jjrn6fv14ue9wlfpby1eo64; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.member_auth_providers
    ADD CONSTRAINT fkl5jjrn6fv14ue9wlfpby1eo64 FOREIGN KEY (member_id) REFERENCES public.member(id);


--
-- PostgreSQL database dump complete
--

\unrestrict aVnQEZttTqEEp0PUaa8uRcTLT1Hq1LQrqhOsYVc2QE7B3uV03hvqP50EYZmJy9w

