--
-- PostgreSQL database dump
--

\restrict ra345RGiiyGwX2sDgyG6tsrntqhUNJUAVs2kFFkYFb2cIdw9VxG4qsEuLfv3Pl6

-- Dumped from database version 15.4 (Debian 15.4-1.pgdg110+1)
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: member_chat_room; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.member_chat_room (
    is_connected boolean NOT NULL,
    is_deleted boolean NOT NULL,
    chat_room_id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    member_id bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL
);


ALTER TABLE public.member_chat_room OWNER TO root;

--
-- Name: member_chat_room_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.member_chat_room ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.member_chat_room_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: member_chat_room; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.member_chat_room (is_connected, is_deleted, chat_room_id, created_at, id, member_id, updated_at) FROM stdin;
f	f	1	2026-02-01 00:06:24.666951+09	1	2	2026-02-01 00:06:24.666951+09
t	f	1	2026-02-01 00:07:35.652688+09	2	3	2026-02-01 00:07:35.652688+09
\.


--
-- Name: member_chat_room_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.member_chat_room_id_seq', 2, true);


--
-- Name: member_chat_room member_chat_room_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.member_chat_room
    ADD CONSTRAINT member_chat_room_pkey PRIMARY KEY (id);


--
-- Name: member_chat_room uk_mcr_member_room; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.member_chat_room
    ADD CONSTRAINT uk_mcr_member_room UNIQUE (member_id, chat_room_id);


--
-- Name: idx_mcr_chat_room_id; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX idx_mcr_chat_room_id ON public.member_chat_room USING btree (chat_room_id);


--
-- Name: idx_mcr_member_id; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX idx_mcr_member_id ON public.member_chat_room USING btree (member_id);


--
-- Name: idx_mcr_member_room; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX idx_mcr_member_room ON public.member_chat_room USING btree (member_id, chat_room_id);


--
-- Name: member_chat_room_member_id_chat_room_id; Type: INDEX; Schema: public; Owner: root
--

CREATE UNIQUE INDEX member_chat_room_member_id_chat_room_id ON public.member_chat_room USING btree (member_id, chat_room_id);


--
-- PostgreSQL database dump complete
--

\unrestrict ra345RGiiyGwX2sDgyG6tsrntqhUNJUAVs2kFFkYFb2cIdw9VxG4qsEuLfv3Pl6

