--
-- PostgreSQL database dump
--

\restrict YdDTH9xXVfwTGgwqlDrsHy3eBBkAqgUmhmkEBw8jahU0k3lkABOwqBOqgHIF3RK

-- Dumped from database version 15.4 (Debian 15.4-1.pgdg110+1)
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: member; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.member (
    birth date,
    is_deleted boolean,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    email character varying(50),
    login_id character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255),
    CONSTRAINT member_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying])::text[])))
);


ALTER TABLE public.member OWNER TO root;

--
-- Name: member_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.member ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.member_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: member; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.member (birth, is_deleted, created_at, id, updated_at, email, login_id, password, role) FROM stdin;
\N	f	2026-01-30 20:45:08.970814+09	1	2026-01-30 20:45:08.970814+09	\N	aaaaa	$2a$10$UDtgzw55WUnYzSh.bQvB/e.6jFIhIxs1FsC0WRQkE/XDFvsBJmHIO	USER
\N	f	2026-01-30 20:45:15.587955+09	2	2026-01-30 20:45:15.587955+09	\N	bbbbb	$2a$10$yGdpPnqAa96iENhR10vl4el0ssqgnukz28VCWy7qb9lG1jigjSIxG	USER
\N	f	2026-01-30 20:45:22.505579+09	3	2026-01-30 20:45:22.505579+09	\N	ccccc	$2a$10$5vRAeg9sSKHLVWKuh9QfmuyzbuGP9kcgNXt5jQjpu152.SrjYvj.C	USER
\N	f	2026-01-30 20:45:29.930382+09	4	2026-01-30 20:45:29.930382+09	\N	ddddd	$2a$10$cvV/4OH3iZQVqzpzruGiaenCd.lO.kFKzxEQlOeA96QKgJxT0DBxq	USER
\N	f	2026-01-30 20:45:36.060457+09	5	2026-01-30 20:45:36.060457+09	\N	eeeee	$2a$10$qK5kt95PeBA1ZAulkZnpwu9xjDpmyX5MsAmTDMQloPLZjQkMjU/WK	USER
\N	f	2026-01-30 23:06:28.045761+09	6	2026-01-30 23:06:28.045761+09	\N	asdfasdf	$2a$10$dp47.40ilNnQMiOTSvWBEOS9DujSc9ZhmA1fWMNDMVJf0sw3G.cDi	USER
\N	f	2026-01-31 20:07:45.573691+09	7	2026-01-31 20:07:45.573691+09	\N	fffff	$2a$10$0RdwwcmgdIKLewhJCbCFpePVhM4U3qic.2j38uBDhKaKwDt.iMr3S	USER
\N	f	2026-01-31 20:08:43.903157+09	8	2026-01-31 20:08:43.903157+09	\N	ggggg	$2a$10$jtRiA8T4woGt5FwXr8mv3uYlCwteCrV6nEoQq5Wd5E1d6iNGwAlP6	USER
\.


--
-- Name: member_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.member_id_seq', 8, true);


--
-- Name: member member_email_key; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.member
    ADD CONSTRAINT member_email_key UNIQUE (email);


--
-- Name: member member_login_id_key; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.member
    ADD CONSTRAINT member_login_id_key UNIQUE (login_id);


--
-- Name: member member_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.member
    ADD CONSTRAINT member_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict YdDTH9xXVfwTGgwqlDrsHy3eBBkAqgUmhmkEBw8jahU0k3lkABOwqBOqgHIF3RK

