--
-- PostgreSQL database dump
--

\restrict 0zqeecX5Chx2SGV1DEMfWqiLx95lArYH184fTaL2AxqumG5RB0AVkMgBsbqdpya

-- Dumped from database version 15.4 (Debian 15.4-1.pgdg110+1)
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: mission; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.mission (
    is_deleted boolean,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    title character varying(20),
    description character varying(255),
    keyword character varying(20)
);


ALTER TABLE public.mission OWNER TO root;

--
-- Name: mission_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.mission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: mission; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.mission (is_deleted, created_at, id, updated_at, title, description, keyword) FROM stdin;
f	2026-01-30 20:44:38.166423+09	1	2026-01-30 20:44:38.166423+09	맨홀 촬영하기	경찰의 포위망이 좁혀오고 있습니다! 주변의 맨홀을 촬영하여 하수도를 통해 탈출 경로를 확보하세요.	manhole
f	2026-01-30 20:44:38.166423+09	2	2026-01-30 20:44:38.166423+09	자전거 촬영하기	신속한 이동이 필요합니다! 근처의 자전거를 찾아 촬영하고 도주 수단을 확보하세요.	bicycle
f	2026-01-30 20:44:38.166423+09	3	2026-01-30 20:44:38.166423+09	오토바이 촬영하기	추격전이 예상됩니다! 오토바이를 촬영하여 더 빠른 속도로 도주하세요.	motorcycle
f	2026-01-30 20:44:38.166423+09	4	2026-01-30 20:44:38.166423+09	자동차 촬영하기	강력한 이동 수단이 필요합니다! 차량을 촬영하여 안전한 은신처까지 거리를 벌리세요.	car
f	2026-02-02 20:53:11.199594+09	13	2026-02-02 20:53:11.199594+09	경찰차 촬영하기	가장 위험한 곳이 가장 안전한 법! 경찰차를 촬영하여 대범함을 증명하고 수사망을 비웃어주세요.	police_car
f	2026-02-02 20:53:11.199594+09	14	2026-02-02 20:53:11.199594+09	스타벅스 로고 촬영하기	도심 속 은신처가 필요합니다. 스타벅스를 촬영하고 수많은 인파 속에 자연스럽게 섞이세요.	starbucks
f	2026-02-02 20:53:11.199594+09	15	2026-02-02 20:53:11.199594+09	버스 촬영하기	복잡한 노선만큼 확실한 도주로는 없습니다. 버스를 촬영하여 추적을 따돌릴 이동 수단을 확보하세요.	bus
f	2026-01-30 20:44:38.166423+09	10	2026-01-30 20:44:38.166423+09	CCTV 촬영하기	감시 카메라에 노출되었습니다! CCTV를 촬영하여 시스템을 무력화하고 흔적을 지우세요.	cctv
f	2026-01-30 20:44:38.166423+09	11	2026-01-30 20:44:38.166423+09	축구 골대 촬영하기	경찰의 포위망이 좁혀오고 있습니다! 주변의 축구 골대를 촬영하여 당신의 위치를 추적하지 못하게 만드세요.	soccer_goal
f	2026-01-30 20:44:38.166423+09	12	2026-01-30 20:44:38.166423+09	농구 골대 촬영하기	경찰의 포위망이 좁혀오고 있습니다! 주변의 농구 골대를 촬영하여 당신의 위치를 추적하지 못하게 만드세요.	basketball_hoop
f	2026-02-02 20:53:11.199594+09	16	2026-02-02 20:53:11.199594+09	버스 촬영하기	복잡한 노선만큼 확실한 도주로는 없습니다. 버스를 촬영하여 추적을 따돌릴 이동 수단을 확보하세요.	bus
f	2026-01-30 20:44:38.166423+09	5	2026-01-30 20:44:38.166423+09	자판기 촬영하기	도주 중 목이 마르군요! 자판기를 촬영하여 갈증을 해소하고 잠시 숨을 고르세요.	vending_machine
f	2026-01-30 20:44:38.166423+09	6	2026-01-30 20:44:38.166423+09	강아지 촬영하기	경찰견의 감시가 심합니다! 주변의 강아지를 촬영하여 경찰견의 주의를 돌리세요.	dog
f	2026-01-30 20:44:38.166423+09	7	2026-01-30 20:44:38.166423+09	고양이 촬영하기	지붕 위를 자유롭게 다니는 고양이처럼, 고양이를 촬영하여 은밀한 이동 경로를 찾아내세요.	cat
f	2026-01-30 20:44:38.166423+09	8	2026-01-30 20:44:38.166423+09	가로등 촬영하기	밤이 깊어갑니다! 가로등을 촬영하여 어둠 속에서 시야를 확보하고 동태를 살피세요.	street_light
f	2026-01-30 20:44:38.166423+09	9	2026-01-30 20:44:38.166423+09	벤치 촬영하기	잠시 쉬어갈 시간이 필요합니다! 벤치를 촬영하여 행인인 척 위장해 경찰을 따돌리세요.	bench
\.


--
-- Name: mission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.mission_id_seq', 1, false);


--
-- Name: mission mission_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.mission
    ADD CONSTRAINT mission_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict 0zqeecX5Chx2SGV1DEMfWqiLx95lArYH184fTaL2AxqumG5RB0AVkMgBsbqdpya

