--
-- PostgreSQL database dump
--

\restrict CsOmnOfJwSouT52RF2FGhcyevaR4TYaQbON7FWvCHy1crwx9h0cUYi40xQa0vzU

-- Dumped from database version 15.4 (Debian 15.4-1.pgdg110+1)
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: refresh_token; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.refresh_token (
    is_deleted boolean,
    created_at timestamp(6) with time zone NOT NULL,
    expired_at timestamp(6) with time zone,
    id bigint NOT NULL,
    member_id bigint NOT NULL,
    revoked_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone NOT NULL,
    device_id character varying(255),
    refresh_token character varying(255) NOT NULL
);


ALTER TABLE public.refresh_token OWNER TO root;

--
-- Name: refresh_token_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.refresh_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: refresh_token; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.refresh_token (is_deleted, created_at, expired_at, id, member_id, revoked_at, updated_at, device_id, refresh_token) FROM stdin;
\.


--
-- Name: refresh_token_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.refresh_token_id_seq', 1, false);


--
-- Name: refresh_token refresh_token_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT refresh_token_pkey PRIMARY KEY (id);


--
-- Name: refresh_token fk5gdbafb2i76hk1ai18ah6an4w; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT fk5gdbafb2i76hk1ai18ah6an4w FOREIGN KEY (member_id) REFERENCES public.member(id);


--
-- PostgreSQL database dump complete
--

\unrestrict CsOmnOfJwSouT52RF2FGhcyevaR4TYaQbON7FWvCHy1crwx9h0cUYi40xQa0vzU

