--
-- PostgreSQL database dump
--

\restrict N6jUrJsIFKHUkfTBPt68NdS47HIZ56UqnYeg8Vkpxd6JSWt6cNsbrs6wfgNunpQ

-- Dumped from database version 15.4 (Debian 15.4-1.pgdg110+1)
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: reports; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.reports (
    is_deleted boolean,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    reporter_id bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    detail text,
    reason character varying(255) NOT NULL,
    reported_nickname character varying(255) NOT NULL,
    status character varying(255),
    CONSTRAINT reports_reason_check CHECK (((reason)::text = ANY ((ARRAY['ABUSE'::character varying, 'CHEAT'::character varying, 'HATE'::character varying, 'OTHER'::character varying])::text[]))),
    CONSTRAINT reports_status_check CHECK (((status)::text = ANY ((ARRAY['RECEIVED'::character varying, 'COMPLETED'::character varying])::text[])))
);


ALTER TABLE public.reports OWNER TO root;

--
-- Name: reports_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.reports ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reports_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: reports; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.reports (is_deleted, created_at, id, reporter_id, updated_at, detail, reason, reported_nickname, status) FROM stdin;
\.


--
-- Name: reports_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.reports_id_seq', 1, false);


--
-- Name: reports reports_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.reports
    ADD CONSTRAINT reports_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict N6jUrJsIFKHUkfTBPt68NdS47HIZ56UqnYeg8Vkpxd6JSWt6cNsbrs6wfgNunpQ

