-- 0. PostGIS 확장 활성화 (최초 1회 실행 필요)
CREATE
EXTENSION IF NOT EXISTS postgis;

-- =============================
-- 1. MEMBER & SECURITY
-- =============================
CREATE TABLE member
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_id   VARCHAR(20) UNIQUE NOT NULL,
    password   VARCHAR(255)       NOT NULL,
    email      VARCHAR(50) UNIQUE,
    birth      DATE,
    status     VARCHAR(10) DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE member_auth_providers
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id         BIGINT       NOT NULL REFERENCES member (id) ON DELETE CASCADE,
    provider          VARCHAR(10)  NOT NULL,
    provider_user_key VARCHAR(255) NOT NULL,
    connected_at      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_provider_user UNIQUE (provider, provider_user_key)
);

CREATE TABLE member_profile
(
    member_id  BIGINT PRIMARY KEY REFERENCES member (id) ON DELETE CASCADE,
    nickname   VARCHAR(20),
    avatar_url VARCHAR(255),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE refresh_token
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id     BIGINT      NOT NULL REFERENCES member (id) ON DELETE CASCADE,
    refresh_token TEXT        NOT NULL,
    device_id     VARCHAR(255),
    expired_at    TIMESTAMPTZ NOT NULL,
    revoked_at    TIMESTAMPTZ,
    created_at    TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- =============================
-- 2. STATS (Vertical Partitioning)
-- =============================
CREATE TABLE member_stat
(
    member_id   BIGINT PRIMARY KEY REFERENCES member (id) ON DELETE CASCADE,
    total_games INT DEFAULT 0,
    wins        INT DEFAULT 0,
    loses       INT DEFAULT 0,
    police_game INT DEFAULT 0,
    thief_game  INT DEFAULT 0
);

CREATE TABLE member_stat_thief
(
    member_id            BIGINT PRIMARY KEY REFERENCES member (id) ON DELETE CASCADE,
    escape_count         INT DEFAULT 0,
    total_mission_count  INT DEFAULT 0,
    longest_survival_sec INT DEFAULT 0,
    average_survival_sec INT DEFAULT 0,
    grade_thief          VARCHAR(10)
);

CREATE TABLE member_stat_police
(
    member_id            BIGINT PRIMARY KEY REFERENCES member (id) ON DELETE CASCADE,
    total_arrest_count   INT DEFAULT 0,
    most_arrests_in_game INT DEFAULT 0,
    grade_police         VARCHAR(10)
);

-- =============================
-- 3. CHAT
-- =============================
CREATE TABLE chat_room
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(255) NOT NULL,
    sido        VARCHAR(20),
    description TEXT,
    created_at  TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE join_chat_room
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id    BIGINT NOT NULL REFERENCES member (id),
    chat_room_id BIGINT NOT NULL REFERENCES chat_room (id) ON DELETE CASCADE,
    created_at   TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_member_room UNIQUE (member_id, chat_room_id)
);

-- =============================
-- 4. GAME & PostGIS
-- =============================
CREATE TABLE game
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    host_user_id BIGINT NOT NULL REFERENCES member (id),
    start_time   TIMESTAMPTZ,
    end_time     TIMESTAMPTZ,
    status       VARCHAR(20),
    win_team     VARCHAR(20),
    room_code    VARCHAR(10),
    created_at   TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE game_setting
(
    game_id         BIGINT PRIMARY KEY REFERENCES game (id) ON DELETE CASCADE,
    time_limit_sec  INT,
    police_count    INT,
    thief_count     INT,
    boundary_geo    GEOMETRY(POLYGON, 4326),
    prison_location GEOMETRY(POINT, 4326),
    updated_at      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
-- PostGIS 공간 인덱스
CREATE INDEX idx_game_setting_boundary ON game_setting USING GIST (boundary_geo);
CREATE INDEX idx_game_setting_prison ON game_setting USING GIST (prison_location);

CREATE TABLE game_member
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id        BIGINT NOT NULL REFERENCES game (id) ON DELETE CASCADE,
    member_id      BIGINT NOT NULL REFERENCES member (id),
    serial_code    VARCHAR(255),
    given_position VARCHAR(10),
    ready          BOOLEAN DEFAULT FALSE,
    status         VARCHAR(10),
    CONSTRAINT uk_game_member UNIQUE (game_id, member_id)
);

-- =============================
-- 5. MISSION & LOGS
-- =============================
CREATE TABLE mission
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(50),
    description VARCHAR(255),
    created_at  TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE game_mission
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id      BIGINT NOT NULL REFERENCES game (id) ON DELETE CASCADE,
    mission_id   BIGINT NOT NULL REFERENCES mission (id),
    completed_by BIGINT REFERENCES member (id),
    completed_at TIMESTAMPTZ,
    status       VARCHAR(10),
    created_at   TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE game_news
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id    BIGINT NOT NULL REFERENCES game (id) ON DELETE CASCADE,
    title      VARCHAR(255),
    contents   VARCHAR(255),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE game_skill
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id  BIGINT NOT NULL REFERENCES member (id),
    game_id    BIGINT NOT NULL REFERENCES game (id) ON DELETE CASCADE,
    is_used    BOOLEAN     DEFAULT FALSE,
    used_at    TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_game_skill UNIQUE (game_id, member_id)
);

-- 성능을 위한 일반 인덱스들
CREATE INDEX idx_game_news_game_id ON game_news (game_id);
CREATE INDEX idx_game_member_game ON game_member (game_id);
CREATE INDEX idx_refresh_token_member ON refresh_token (member_id);